import { Product, Order } from "./types"

export const categories = [
  "Proteins",
  "Creatine",
  "Pre-Workout",
  "Vitamins",
  "Fat Burners",
  "Amino Acids",
]

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Whey Protein",
    description: "High-quality whey protein, 2kg. Ideal for post-workout recovery.",
    price: 49.99,
    category: "Proteins",
    image: "https://images.unsplash.com/photo-1593111774240-d529f12cf98b?w=400",
    isBestSeller: true,
  },
  {
    id: "2",
    name: "Creatine Monohydrate",
    description: "Pure creatine powder, 500g. Increases strength and muscle mass.",
    price: 24.99,
    category: "Creatine",
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
    isBestSeller: true,
  },
  {
    id: "3",
    name: "Explosive Pre-Workout",
    description: "Energy formula with caffeine and beta-alanine, 300g. Improves performance.",
    price: 34.99,
    category: "Pre-Workout",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
    isBestSeller: true,
  },
  {
    id: "4",
    name: "Complete Multivitamin",
    description: "Vitamin and mineral complex, 120 capsules. Complete nutritional support.",
    price: 19.99,
    category: "Vitamins",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
    isBestSeller: false,
  },
  {
    id: "5",
    name: "Thermogenic Fat Burner",
    description: "Advanced thermogenic formula, 120 capsules. Accelerates metabolism.",
    price: 39.99,
    category: "Fat Burners",
    image: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=400",
    isBestSeller: false,
  },
  {
    id: "6",
    name: "BCAA 2:1:1",
    description: "Branched-chain amino acids, 300g. Prevents muscle catabolism.",
    price: 29.99,
    category: "Amino Acids",
    image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400",
    isBestSeller: false,
  },
  {
    id: "7",
    name: "Vegan Protein",
    description: "Pea and rice protein, 1.5kg. 100% plant-based and lactose-free.",
    price: 44.99,
    category: "Proteins",
    image: "https://images.unsplash.com/photo-1593111774240-d529f12cf98b?w=400",
    isBestSeller: false,
  },
  {
    id: "8",
    name: "Creatine HCL",
    description: "Creatine hydrochloride, 300g. Higher solubility and absorption.",
    price: 27.99,
    category: "Creatine",
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
    isBestSeller: false,
  },
  {
    id: "9",
    name: "Caffeine-Free Pre-Workout",
    description: "Stimulant-free formula, 250g. Ideal for evening workouts.",
    price: 32.99,
    category: "Pre-Workout",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
    isBestSeller: false,
  },
  {
    id: "10",
    name: "Vitamin D3 + K2",
    description: "D3 and K2 vitamin complex, 60 capsules. Bone and cardiovascular health.",
    price: 16.99,
    category: "Vitamins",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
    isBestSeller: false,
  },
  {
    id: "11",
    name: "Natural Fat Burner",
    description: "Natural thermogenic extracts, 90 capsules. No artificial stimulants.",
    price: 35.99,
    category: "Fat Burners",
    image: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=400",
    isBestSeller: false,
  },
  {
    id: "12",
    name: "Glutamine Powder",
    description: "Pure L-glutamine, 500g. Muscle recovery and immune system support.",
    price: 22.99,
    category: "Amino Acids",
    image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400",
    isBestSeller: false,
  },
]

export const dummyOrders: Order[] = [
  {
    id: "ORD-001",
    customerName: "John Smith",
    customerEmail: "john.smith@email.com",
    customerPhone: "+1 555 123 4567",
    shippingAddress: "123 Main Street",
    shippingCity: "New York",
    shippingZipCode: "10001",
    status: "pending",
    createdAt: "2024-01-15T10:30:00Z",
    items: [
      { product: products[0], quantity: 1 },
      { product: products[1], quantity: 1 },
    ],
    total: 74.98,
  },
  {
    id: "ORD-002",
    customerName: "Sarah Johnson",
    customerEmail: "sarah.johnson@email.com",
    customerPhone: "+1 555 234 5678",
    shippingAddress: "45 Liberty Avenue",
    shippingCity: "Los Angeles",
    shippingZipCode: "90001",
    status: "processing",
    createdAt: "2024-01-14T14:20:00Z",
    items: [
      { product: products[2], quantity: 1 },
      { product: products[3], quantity: 1 },
    ],
    total: 54.98,
  },
  {
    id: "ORD-003",
    customerName: "Michael Brown",
    customerEmail: "michael.brown@email.com",
    customerPhone: "+1 555 345 6789",
    shippingAddress: "7 Spain Plaza",
    shippingCity: "Chicago",
    shippingZipCode: "60601",
    status: "shipped",
    createdAt: "2024-01-13T09:15:00Z",
    items: [
      { product: products[0], quantity: 1 },
      { product: products[4], quantity: 1 },
    ],
    total: 89.98,
  },
  {
    id: "ORD-004",
    customerName: "Emily Davis",
    customerEmail: "emily.davis@email.com",
    customerPhone: "+1 555 456 7890",
    shippingAddress: "89 Grand Avenue",
    shippingCity: "Houston",
    shippingZipCode: "77001",
    status: "delivered",
    createdAt: "2024-01-12T16:45:00Z",
    items: [
      { product: products[5], quantity: 1 },
    ],
    total: 29.99,
  },
  {
    id: "ORD-005",
    customerName: "David Wilson",
    customerEmail: "david.wilson@email.com",
    customerPhone: "+1 555 567 8901",
    shippingAddress: "12 Main Avenue",
    shippingCity: "Phoenix",
    shippingZipCode: "85001",
    status: "pending",
    createdAt: "2024-01-11T11:30:00Z",
    items: [
      { product: products[6], quantity: 1 },
      { product: products[7], quantity: 1 },
    ],
    total: 72.98,
  },
  {
    id: "ORD-006",
    customerName: "Jessica Martinez",
    customerEmail: "jessica.martinez@email.com",
    customerPhone: "+1 555 678 9012",
    shippingAddress: "34 New Street",
    shippingCity: "Philadelphia",
    shippingZipCode: "19001",
    status: "processing",
    createdAt: "2024-01-10T13:20:00Z",
    items: [
      { product: products[8], quantity: 1 },
    ],
    total: 32.99,
  },
  {
    id: "ORD-007",
    customerName: "Robert Taylor",
    customerEmail: "robert.taylor@email.com",
    customerPhone: "+1 555 789 0123",
    shippingAddress: "56 Main Plaza",
    shippingCity: "San Antonio",
    shippingZipCode: "78201",
    status: "shipped",
    createdAt: "2024-01-09T15:10:00Z",
    items: [
      { product: products[9], quantity: 1 },
      { product: products[10], quantity: 1 },
    ],
    total: 52.98,
  },
  {
    id: "ORD-008",
    customerName: "Amanda Anderson",
    customerEmail: "amanda.anderson@email.com",
    customerPhone: "+1 555 890 1234",
    shippingAddress: "78 Central Avenue",
    shippingCity: "San Diego",
    shippingZipCode: "92101",
    status: "delivered",
    createdAt: "2024-01-08T10:00:00Z",
    items: [
      { product: products[11], quantity: 1 },
    ],
    total: 22.99,
  },
]

